// <auto-generated />
using HomeManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeManagement.Migrations
{
    [DbContext(typeof(HomeManagementDbContext))]
<<<<<<< HEAD:HomeManagement/Migrations/20250913130714_Initial.Designer.cs
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD:HomeManagement/Migrations/20250913130714_Initial.Designer.cs
=======
<<<<<<< HEAD:HomeManagement/Migrations/20250913130714_Initial.Designer.cs
<<<<<<< HEAD:HomeManagement/Migrations/20250914105204_Initial.Designer.cs
<<<<<<< HEAD:HomeManagement/Migrations/20250913130714_Initial.Designer.cs
=======
=======
>>>>>>> 33bd328 (Add Dashboard, Add Auth):HomeManagement/Migrations/20250914105204_Initial.Designer.cs
<<<<<<< HEAD:HomeManagement/Migrations/20250913130714_Initial.Designer.cs
<<<<<<< HEAD
=======
>>>>>>> a319cbf (Get Status, Update to .NET 10)
=======
=======
<<<<<<< HEAD:HomeManagement/Migrations/20250913130714_Initial.Designer.cs
>>>>>>> 5be7bab (Add Dashboard, Add Auth):HomeManagement/Migrations/20250914105204_Initial.Designer.cs
>>>>>>> a123fff (Add Dashboard, Add Auth):HomeManagement/Migrations/20250914105204_Initial.Designer.cs
>>>>>>> 3d0106c (Add Dashboard, Add Auth):HomeManagement/Migrations/20250914105204_Initial.Designer.cs
<<<<<<< HEAD:HomeManagement/Migrations/20250913130714_Initial.Designer.cs
=======
<<<<<<< HEAD
=======
>>>>>>> a319cbf (Get Status, Update to .NET 10)
>>>>>>> 0de0591 (Get Status, Update to .NET 10):HomeManagement/Migrations/20250913130714_Initial.Designer.cs
>>>>>>> d4eca16 (Get Status, Update to .NET 10):HomeManagement/Migrations/20250914105204_Initial.Designer.cs
=======
<<<<<<< HEAD:HomeManagement/Migrations/20250913130714_Initial.Designer.cs
>>>>>>> 5e15dfb (Refactor and enhance device management system)
=======
>>>>>>> 33bd328 (Add Dashboard, Add Auth):HomeManagement/Migrations/20250914105204_Initial.Designer.cs
>>>>>>> 0e1ba11 (Add Dashboard, Add Auth):HomeManagement/Migrations/20250914105204_Initial.Designer.cs
<<<<<<<< HEAD:HomeManagement/Migrations/20250913130714_Initial.Designer.cs
    [Migration("20250913130714_Initial")]
========
    [Migration("20251001124631_Initial")]
>>>>>>>> 3548e6a (Get Status, Update to .NET 10):HomeManagement/Migrations/20251001124631_Initial.Designer.cs
<<<<<<< HEAD
<<<<<<< HEAD
=======
<<<<<<< HEAD:HomeManagement/Migrations/20250913130714_Initial.Designer.cs
    [Migration("20250913130714_Initial")]
>>>>>>> eeff7ac (Refactor and enhance device management system)
<<<<<<< HEAD:HomeManagement/Migrations/20250913130714_Initial.Designer.cs
=======
<<<<<<< HEAD:HomeManagement/Migrations/20250913130714_Initial.Designer.cs
<<<<<<< HEAD:HomeManagement/Migrations/20250914105204_Initial.Designer.cs
<<<<<<< HEAD:HomeManagement/Migrations/20250913130714_Initial.Designer.cs
=======
=======
>>>>>>> 33bd328 (Add Dashboard, Add Auth):HomeManagement/Migrations/20250914105204_Initial.Designer.cs
=======
<<<<<<< HEAD:HomeManagement/Migrations/20250913130714_Initial.Designer.cs
>>>>>>> a319cbf (Get Status, Update to .NET 10)
=======
    [Migration("20250914105204_Initial")]
>>>>>>> 0efb677 (Add Dashboard, Add Auth):HomeManagement/Migrations/20250914105204_Initial.Designer.cs
>>>>>>> 5be7bab (Add Dashboard, Add Auth):HomeManagement/Migrations/20250914105204_Initial.Designer.cs
>>>>>>> a123fff (Add Dashboard, Add Auth):HomeManagement/Migrations/20250914105204_Initial.Designer.cs
>>>>>>> 3d0106c (Add Dashboard, Add Auth):HomeManagement/Migrations/20250914105204_Initial.Designer.cs
<<<<<<< HEAD:HomeManagement/Migrations/20250913130714_Initial.Designer.cs
=======
=======
>>>>>>> a319cbf (Get Status, Update to .NET 10)
>>>>>>> 0de0591 (Get Status, Update to .NET 10):HomeManagement/Migrations/20250913130714_Initial.Designer.cs
>>>>>>> d4eca16 (Get Status, Update to .NET 10):HomeManagement/Migrations/20250914105204_Initial.Designer.cs
=======
<<<<<<< HEAD:HomeManagement/Migrations/20250913130714_Initial.Designer.cs
=======
    [Migration("20250913130714_Initial")]
>>>>>>> eeff7ac (Refactor and enhance device management system)
>>>>>>> 5e15dfb (Refactor and enhance device management system)
=======
>>>>>>> 33bd328 (Add Dashboard, Add Auth):HomeManagement/Migrations/20250914105204_Initial.Designer.cs
>>>>>>> 0e1ba11 (Add Dashboard, Add Auth):HomeManagement/Migrations/20250914105204_Initial.Designer.cs
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 5e15dfb (Refactor and enhance device management system)
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107");
=======
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");
>>>>>>> eeff7ac (Refactor and enhance device management system)
<<<<<<< HEAD
=======
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107");
>>>>>>> a319cbf (Get Status, Update to .NET 10)
=======
>>>>>>> 5e15dfb (Refactor and enhance device management system)

            modelBuilder.Entity("HomeManagement.Device", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("HomeManagement.Device", b =>
                {
                    b.OwnsMany("HomeManagement.DeviceAction", "Actions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Command")
                                .IsRequired()
                                .HasColumnType("TEXT");

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> a319cbf (Get Status, Update to .NET 10)
=======
>>>>>>> 5e15dfb (Refactor and enhance device management system)
                            b1.Property<string>("CommandArgs")
                                .HasColumnType("TEXT");

                            b1.Property<int>("CommandType")
                                .HasColumnType("INTEGER");

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> eeff7ac (Refactor and enhance device management system)
=======
>>>>>>> a319cbf (Get Status, Update to .NET 10)
=======
=======
>>>>>>> eeff7ac (Refactor and enhance device management system)
>>>>>>> 5e15dfb (Refactor and enhance device management system)
                            b1.Property<string>("DeviceName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("DeviceName");

                            b1.ToTable("DeviceActions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DeviceName");
                        });

                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
